package com.stefanini.model;
// Generated 07/11/2016 12:04:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Telefones generated by hbm2java
 */
public class Telefones implements java.io.Serializable {

	private Telefones id;
	private int idTipoTelefone;
	private int numero;
	private int ddd;
	private int cpfProprietario;

	public Telefones() {
	}

	public Telefones(Telefones id, int idTipoTelefone,int numero, int ddd, int cpfProprietario) {
		this.id = id;
		this.idTipoTelefone = idTipoTelefone;
		this.numero = numero;
		this.ddd = ddd;
		this.cpfProprietario = cpfProprietario;
	}



	@AttributeOverrides({ @AttributeOverride(name = "numero", column = @Column(name = "numero", nullable = false)),
			@AttributeOverride(name = "ddd", column = @Column(name = "ddd", nullable = false)),
			@AttributeOverride(name = "cpfProprietario", column = @Column(name = "cpfProprietario", nullable = false)) })
	public Telefones getId() {
		return this.id;
	}

	public void setId(Telefones id) {
		this.id = id;
	}

	@Column(name = "idTipoTelefone", nullable = false)
	public int getIdTipoTelefone() {
		return this.idTipoTelefone;
	}

	public void setIdTipoTelefone(int idTipoTelefone) {
		this.idTipoTelefone = idTipoTelefone;
	}
	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@Column(name = "ddd", nullable = false)
	public int getDdd() {
		return this.ddd;
	}

	public void setDdd(int ddd) {
		this.ddd = ddd;
	}

	@Column(name = "cpfProprietario", nullable = false)
	public int getCpfProprietario() {
		return this.cpfProprietario;
	}

	public void setCpfProprietario(int cpfProprietario) {
		this.cpfProprietario = cpfProprietario;
	}
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Telefones))
			return false;
		Telefones castOther = (Telefones) other;

		return (this.getNumero() == castOther.getNumero()) && (this.getDdd() == castOther.getDdd())
				&& (this.getCpfProprietario() == castOther.getCpfProprietario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumero();
		result = 37 * result + this.getDdd();
		result = 37 * result + this.getCpfProprietario();
		return result;
	}


}
